---
k3s_backup_packages:
  - nfs-common

k3s_backup_nfs_server: 192.168.0.102
k3s_backup_nfs_export: /mnt/user/k3s-backups
k3s_backup_mount_path: /mnt/k3s-backups
k3s_backup_mount_options: >-
  rw,hard,vers=3,_netdev,nofail,x-systemd.automount,x-systemd.device-timeout=10s

k3s_backup_snapshot_dir: /var/lib/rancher/k3s/server/db/snapshots
k3s_backup_token_path: /var/lib/rancher/k3s/server/token

k3s_backup_script_path: /usr/local/sbin/k3s-backup
